version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
      - MAVEN_HOME=/usr/share/maven
    command: [ "mvn", "spring-boot:run" ]
    depends_on:
      - db
      - cache

  cache:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - devcontainer-network
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - TZ=UTC
      - LANG=en_US.UTF-8
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  devcontainer-network:
    driver: bridge
